# 1️⃣ ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: awesomeecom
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://cart-db:5432/db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_CACHE_TYPE: redis
  SPRING_DATA_REDIS_HOST: redis
  EUREKA_INSTANCE_HOSTNAME: cart-service
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_GROUP_ID: cart-service
---
# 2️⃣ Secret
apiVersion: v1
kind: Secret
metadata:
  name: cart-service-secret
  namespace: awesomeecom
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
