apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: awesomeecom
type: Opaque
stringData:
  STRIPE_API_KEY: your_stripe_api_key
  STRIPE_WEBHOOK_SECRET: your_stripe_webhook_secret
