server:
  port: 4006

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: http://customer-service:4000
              predicates:
                - Path=/customer/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/cart/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notify/**
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests:
              enabled: true
      percentiles:
        http:
          server:
            requests: 0.5,0.9,0.95,0.99
  prometheus:
    metrics:
      export:
        enabled: true
