spring.application.name=customer-service
server.port=4000
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5000/db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
jwt.secret=1p5jPZQO3szEwYcFvC3DshVwrv2h6l9Pwz5X2iR8i3kC5a9gPZ7xT2dGxJ9wVf6uT5lC4rN3bG6fV7dL8jM9aK2pR4uT1wE8qMJ
