### Registration
POST /customer/register HTTP/1.1
Host: localhost:4006
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe",
  "name": "John Doe",
  "email": "john.doe@example.com",
  "address": "123 Main Street, City",
  "phone": "john_doe",
  "password": "Password123",
  "confirmPassword": "Password123"
}


### Login
POST /customer/login HTTP/1.1
Host: localhost:4006
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe",
  "password": "Password123"
}

> {% client.global.set("token", response.body.token) %}

### Validate Token
GET http://localhost:4006/customer/validate
Authorization: Bearer {{token}}

### Get Customer Profile
GET http://localhost:4006/customer/me
Authorization: Bearer {{token}}