### GET request to example server
POST localhost:4006/notify/order-confirmation
Content-Type: application/json

{
  "customerName": "Minhaz",
  "email": "mminhazurrahman0@gmail.com",
  "orderId": "bae6ed7f-8304-446c-880d-9068f8661813",
  "orderTotal": "89.99",
  "shippingAddress": "Khilgaon, Dhaka"
}

###