### GET request to example server
POST http://localhost:4006/orders/create-order
Content-Type: application/json

{
  "customerId": "2d9437ff-040e-4479-bae7-4f93e076f199",
  "paymentMethod": "stripe",
  "cartId": "blabla"
}

###
GET http://localhost:4006/orders/bae6ed7f-8304-446c-880d-9068f8661813