### GET request to fetch products
GET http://localhost:4006/products


### Create a product
POST http://localhost:4001/products/create
Content-Type: application/json

{
  "name": "Smart Watch",
  "description": "This is a fantastic smart watch.",
  "category": "Gadgets",
  "brand": "Samsung",
  "price": 89.99,
  "stockQuantity": 100
}
